package model;
// Generated Nov 15, 2015 3:54:50 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Lossinfotype generated by hbm2java
 */
@Entity
@Table(name = "LOSSINFOTYPE", schema = "PUBLIC", catalog = "PUBLIC")
public class Lossinfotype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9025880952642152206L;
	private String claimnumber;
	private Claim claim;
	private String causeoflosscode;
	private Date reporteddate;
	private String lossdescription;

	public Lossinfotype() {
	}

	public Lossinfotype(Claim claim) {
		this.claim = claim;
	}

	public Lossinfotype(Claim claim, String causeoflosscode, Date reporteddate, String lossdescription) {
		this.claim = claim;
		this.causeoflosscode = causeoflosscode;
		this.reporteddate = reporteddate;
		this.lossdescription = lossdescription;
	}

	@Id
	@GenericGenerator(name = "customgenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "claim") )
	@GeneratedValue(generator = "customgenerator")
	@Column(name = "CLAIMNUMBER", unique = true, nullable = false, length = 200)
	public String getClaimnumber() {
		return this.claimnumber;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Lossinfotype [causeoflosscode=" + causeoflosscode + ", reporteddate=" + reporteddate
				+ ", lossdescription=" + lossdescription + "]";
	}

	public void setClaimnumber(String claimnumber) {
		this.claimnumber = claimnumber;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	@Column(name = "CAUSEOFLOSSCODE", length = 200)
	public String getCauseoflosscode() {
		return this.causeoflosscode;
	}

	public void setCauseoflosscode(String causeoflosscode) {
		this.causeoflosscode = causeoflosscode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REPORTEDDATE", length = 10)
	public Date getReporteddate() {
		return this.reporteddate;
	}

	public void setReporteddate(Date reporteddate) {
		this.reporteddate = reporteddate;
	}

	@Column(name = "LOSSDESCRIPTION", length = 200)
	public String getLossdescription() {
		return this.lossdescription;
	}

	public void setLossdescription(String lossdescription) {
		this.lossdescription = lossdescription;
	}

}
