package model;
// Generated Nov 15, 2015 3:54:50 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehicleinfotype generated by hbm2java Vehicleinfotype class is mapped to
 * VEHICLEINFOTYPE table in the database
 * 
 */
@Entity
@Table(name = "VEHICLEINFOTYPE", schema = "PUBLIC", catalog = "PUBLIC")
public class Vehicleinfotype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7036088868901059302L;
	private String licplate;
	private Claim claim;
	private Integer modelyear;
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */

	private String makedescription;
	private String modeldescription;
	private String enginedescription;
	private String exteriorcolor;
	private String vin;
	private String licplatestate;
	private String damagedescription;
	private Date licplateexpdate;
	private Integer mileage;

	public Vehicleinfotype() {
	}

	public Vehicleinfotype(String licplate) {
		this.licplate = licplate;
	}

	public Vehicleinfotype(String licplate, Claim claim, Integer modelyear, String makedescription,
			String modeldescription, String enginedescription, String exteriorcolor, String vin, String licplatestate,
			String damagedescription, Date licplateexpdate, Integer mileage) {
		this.licplate = licplate;
		this.claim = claim;
		this.modelyear = modelyear;
		this.makedescription = makedescription;
		this.modeldescription = modeldescription;
		this.enginedescription = enginedescription;
		this.exteriorcolor = exteriorcolor;
		this.vin = vin;
		this.licplatestate = licplatestate;
		this.damagedescription = damagedescription;
		this.licplateexpdate = licplateexpdate;
		this.mileage = mileage;
	}

	@Id

	@Column(name = "VIN", unique = true, nullable = false, length = 200)
	public String getVin() {
		return this.vin;
	}

	public void setVin(String vin) {
		this.vin = vin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLAIMNUMBER")
	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	@Column(name = "MODELYEAR")
	public Integer getModelyear() {
		return this.modelyear;
	}

	public void setModelyear(Integer modelyear) {
		this.modelyear = modelyear;
	}

	@Column(name = "MAKEDESCRIPTION", length = 200)
	public String getMakedescription() {
		return this.makedescription;
	}

	public void setMakedescription(String makedescription) {
		this.makedescription = makedescription;
	}

	@Column(name = "MODELDESCRIPTION", length = 200)
	public String getModeldescription() {
		return this.modeldescription;
	}

	public void setModeldescription(String modeldescription) {
		this.modeldescription = modeldescription;
	}

	@Column(name = "ENGINEDESCRIPTION", length = 200)
	public String getEnginedescription() {
		return this.enginedescription;
	}

	public void setEnginedescription(String enginedescription) {
		this.enginedescription = enginedescription;
	}

	@Column(name = "EXTERIORCOLOR", length = 200)
	public String getExteriorcolor() {
		return this.exteriorcolor;
	}

	public void setExteriorcolor(String exteriorcolor) {
		this.exteriorcolor = exteriorcolor;
	}

	@Column(name = "LICPLATE", length = 200)
	public String getLicplate() {
		return this.licplate;
	}

	public void setLicplate(String licPlate) {
		this.licplate = licPlate;
	}

	@Column(name = "LICPLATESTATE", length = 200)
	public String getLicplatestate() {
		return this.licplatestate;
	}

	public void setLicplatestate(String licplatestate) {
		this.licplatestate = licplatestate;
	}

	@Column(name = "DAMAGEDESCRIPTION", length = 200)
	public String getDamagedescription() {
		return this.damagedescription;
	}

	public void setDamagedescription(String damagedescription) {
		this.damagedescription = damagedescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LICPLATEEXPDATE", length = 10)
	public Date getLicplateexpdate() {
		return this.licplateexpdate;
	}

	public void setLicplateexpdate(Date licplateexpdate) {
		this.licplateexpdate = licplateexpdate;
	}

	@Column(name = "MILEAGE")
	public Integer getMileage() {
		return this.mileage;
	}

	public void setMileage(Integer mileage) {
		this.mileage = mileage;
	}

	@Override
	public String toString() {
		return "Vehicleinfotype [licplate=" + licplate + ", modelyear=" + modelyear + ", makedescription="
				+ makedescription + ", modeldescription=" + modeldescription + ", enginedescription="
				+ enginedescription + ", exteriorcolor=" + exteriorcolor + ", vin=" + vin + ", licplatestate="
				+ licplatestate + ", damagedescription=" + damagedescription + ", licplateexpdate=" + licplateexpdate
				+ ", mileage=" + mileage + "]";
	}

}
